### ISSUE TITLE
Excuse me, I want to generate a multi-layer network, but why can't I generate a file and keep reporting an error?

### ISSUE THREAD

**Issue by sakuracg** [pbrodka/mLFR-benchmark#2]
Excuse me, I want to generate a multi-layer network, but why can't I generate a file and keep reporting an error?

Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/commons/math/distribution/Distribution         
at com.pl.wroc.pwr.ii.zsi.jlfr.generator.Generator.generate(Generator.java:55)         
at com.pl.wroc.pwr.ii.zsi.jlfr.generator.Generator.perform(Generator.java:45)         
at com.pl.wroc.pwr.ii.zsi.jlfr.generator.GeneratorTask.run(GeneratorTask.java:18)         
at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.ClassNotFoundException: org.apache.commons.math.distribution.Distribution         
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)         
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)         
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)         ... 4 more

**Comment by sakuracg** [comment]
Using a jar application

**Comment by pbrodka** [comment]
Could you please paste the whole error? And tell me exactly what you want to do?

**Comment by sakuracg** [comment]
![QQ图片20220420201119](https://user-images.githubusercontent.com/43086039/164227741-92905571-8ee5-4397-938c-b979c47abb96.png)
![QQ图片20220420201140](https://user-images.githubusercontent.com/43086039/164227752-0b024a75-c4f3-43e9-884b-89683669b6f1.png)
OK, thank you very much for answering my question！
I put two pictures, the first one is my setting parameters, and the second one is the error when I click the generate button. I don't know why this is happening and would like to ask.

**Comment by sakuracg** [comment]
> Could you please paste the whole error? And tell me exactly what you want to do?

I want to generate LFR multiplex networks. I will test and compare community detection algorithms in multiplex networks.

**Comment by sakuracg** [comment]
Hello, I fixed the above problem by changing a computer. However, it only produces a real community file, but no network data file. I would like to ask you why this is. Thanks very much for your answer!
![QQ图片20220420213816](https://user-images.githubusercontent.com/43086039/164243194-2ce74a37-0be9-49ba-8f98-facfd702a04e.png)
.
